services:
  - type: web
    name: focusflow
    plan: free
    env: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn focusflow.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_URL
        fromDatabase:
          name: focusflow-db
          property: connectionString

databases:
  - name: focusflow-db
    plan: free
    databaseName: focusflow
    user: focusflow

